### ISSUE TITLE
What does the safe version refer to here

### ISSUE THREAD

**Issue by yjhmelody** [MaxGraey/bignum.wasm#64] opened 2021-05-18 09:40 UTC
What does the safe version refer to here? Is it similar to checked_op in rust? It seems that it is more convenient to introduce an Option, and in this case, it seems that new types should not be defined

**Comment by MaxGraey** [comment] 2021-05-18 10:02
> Is it similar to checked_op in rust?

Yes, but instead return option we just throw abort.

> It seems that it is more convenient to introduce an Option, and in this case, it seems that new types should not be defined

No, monadic option is good for functional programming when null safety doesn't support on language level. In AssemblyScript we follow typescript paradigm with nullish types.

We need another type due to overflow checking required extra runtime overhead which not always needed.

**Comment by yjhmelody** [comment] 2021-05-18 10:09
> We need another type due to overflow checking required extra runtime overhead which not always needed.

I mean providing the checked_op operator instead of providing a new type and overloading it. Isn’t it troublesome to convert between two types sometimes? The function name also distinguishes the difference in operation, just like in rust

**Comment by MaxGraey** [comment] 2021-05-18 10:14
> I mean providing the checked_op operator instead of providing a new type and overloading it.

I see. I'm not fun of method based safe operations. Some applications like smart contacts required always and only safe operations which will looks very verbose in this case

> The function name also distinguishes the difference in operation, just like in rust

I don't think Rust's approach is good for our case. Rust is low level language which also highly based on trait system. TypeScript / AssemblyScript follow another paradigm.

I don't really understand the general imitation of rust, which actually mimics Ocaml, which in general is a functional language

**Comment by yjhmelody** [comment] 2021-05-18 10:42
Well, in the blockchain or smart contract, I personally think that we should not throw abort directly, but assert every place that needs to be checked, so that we can easily find the wrong place after an abnormal exit or can return an error type to describe error type. This is just a set of chained calls in rust.

And you are right. Many times we don't want to have redundant checks. For example, a type only supports operations with checks. If we don't want to check here (because there is no error in logic), then type conversion is needed here. At least I see in the rust code that many arithmetic operations with checks are interspersed with ordinary operators without checks. Obviously in this case, the safe/unsafe type conversion is more verbose.

I have seen some cases where the maximum or minimum value is returned when overflow (this is really common in blockchain projects, and saturating_op is used in rust). If the function exits directly here, we cannot implement this function based on this API.

Well, it may be more important to have a safe API first, but I reserve my opinion.

**Comment by earlyraven** [comment] 2023-12-21 03:19
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by rookiecdn** [comment] 2024-03-04 07:40
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
ddload, @juaxix, @alexgorbachev, @mistacoda, @cloder, @hammerfunctor, @dovidezra, @pe-ge, @ik5, @kenorb, @alexeypro, @rolltidehero, @leehuffman, @chrisjoyce, @wulrahman, @coin-comachi, @reall0c, @shrynx, @jayrulez, @Zucce05

**Closed as completed** 2024-03-04 09:17 UTC
Labels: question
